spring:
  config:
    activate:
      on-profile: kafka_dev

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      auto-offset-reset: latest
      max-poll-records: 20
      group-id: default
    producer:
      retries: 5
    topics:
      article:
        name: article
        partitions: 4
        replication-factor: 1
      read:
        name: read
        partitions: 8
        replication-factor: 1
      reward:
        name: reward
        partitions: 8
        replication-factor: 1

